export const client = {
  name: "Thames Maintenance Ltd",
  tagline: "Professional Garden Maintenance in High Wycombe — Quality You Can Trust",
  description: "Professional garden maintenance services in High Wycombe and surrounding areas. Trusted local experts with 14 Google reviews.",
  category: "Garden Maintenance",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "High Wycombe",
  county: "",
  postcode: "",
  basedIn: "High Wycombe",
  founderName: "",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.9",
  reviewCount: "14",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Lesley Muddiman", rating: 5, text: "Darren and his team were fabulous, they cleared our very overgrown garden and left it looking clean and tidy, we would highly recommend Thames maintenance Ltd.", date: "8 months ago" },
    { name: "Ethel Wivic", rating: 5, text: "Top Job.    Replaced 5 fence pots damaged in strong winds and also performed other maintenance on fencing not in scope!   All left neat and tidy afterwards.  Great job by Darren  CW", date: "a year ago" },
    { name: "Duncan Graham", rating: 5, text: "Would highly recommend Darren and his team. Prompt, efficient service and restored a much neglected house (gardens and fences) to the original order. Never seen so many weeds and fence ivy disappear  so promptly.", date: "a year ago" },
    { name: "tiago costa", rating: 5, text: "Darren was super helpful and easy to communicate with. The work he carried out as 1st and really went above an beyond. I would use Darren services again has it was reliable but ultimate great service.", date: "3 years ago" },
    { name: "Jerome Cann", rating: 5, text: "I needed some Ivy trimmed right back and tidied on the front of my house a small tree removed and garden tidied. Darren did a great job. Communication was very good, and turned up when arranged. Also came back to do a couple of extras!", date: "3 years ago" },
    { name: "Liz Pollitt", rating: 5, text: "A great service. Darren did a great job clearing leaves, trimming shrubs and generally tidying up the garden. Obtaining a quote, a date for the work and making payment was easy and efficient. Darren very kindly went above and beyond in proving photos as well.", date: "3 years ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Thames Maintenance Ltd | Professional Garden Maintenance in High Wycombe",
    description: "Professional garden maintenance in High Wycombe. 4.9 stars on Google with 14 reviews. Quality workmanship guaranteed.",
  },
};
